<?php

namespace FormArmorBundle\Repository;

/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function listeClientUneSession($idSession)
        {
           $queryBuilder = $this->createQueryBuilder('i');
           $query = $queryBuilder->select(array('i'))
                   ->where($queryBuilder->expr()->eq('i.session_formation', ':idSession'))
                   ->setParameter('idSession', $idSession);
           return $query->getQuery()->getResult();
        }
}
