<?php

namespace FormArmorBundle\Repository;

/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function listeClientUneSession($idSession)
        {
           $queryBuilder = $this->createQueryBuilder('i');
           $query = $queryBuilder->select(array('i'))
                   ->where($queryBuilder->expr()->eq('i.session_formation', ':idSession'))
                   ->setParameter('idSession', $idSession);
           return $query->getQuery()->getResult();
        }
    public function listeMailuneSession($idSession)
        {
            $qb = $this->createQueryBuilder('i');
            $query = $qb->select('c.email')
                    ->join('i.client', 'c')
                    ->where($qb->expr()->eq('i.session_formation', ':idSession'))
                    ->setParameter('idSession', $idSession);
            $lesMail = $query->getQuery()->getArrayResult();
            $lesMailF = [];
            for($i=0;$i<count($lesMail);$i++)
            {
                array_push($lesMailF,$lesMail[$i]['email']);
            }
            return $lesMailF;
        }
}
